### PR TITLE
Fixes 'bin' path, filter duplicated ports, return them as Number and handle errors

### PR DESCRIPTION
**Pull request by at15four2020**

### CODE REVIEW

**Review by Turbine1991 — COMMENTED** [review]
I'm curious if you moved ` process.env.PATH = oldPath;` because it didn't seem to belong at the bottom?

If I recall correctly, this ensures the environment's path in node isn't changed for code outside of the library.

**Review by Turbine1991 — COMMENTED** [review]
Looks good. Apart from the one thing listed. I just need confirmation on the reasoning.

**Comment by at15four2020** [comment]
> I'm curious if you moved ` process.env.PATH = oldPath;` because it didn't seem to belong at the bottom?
> 
> If I recall correctly, this ensures the environment's path in node isn't changed for code outside of the library.

That was to also recover the `oldPath` if any error happens. But yea, that way the `resolve` fires with the "corrent" path too

**Comment by c-ridgway** [comment]
You're right. It's good.

**Comment by c-ridgway** [comment]
Thank you for the contribution. It's now pushed to NPM.

**Pull request merged**
